[package]
name = "evolution"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.5" 
plotters = "0.3.1"
bincode = "1.3"
clap = { version = "4.0", features = ["derive"] }
